apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: subscriber-app
  template:
    metadata:
      labels:
        app: subscriber-app
    spec:
      containers:
      - name: subscriber
        image: subscriber:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
